name: release
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: setup go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          go get -v -u github.com/Songmu/goxz/cmd/goxz
          go get -v -u github.com/tcnksm/ghr
          release_tag=$( git describe --abbrev=0 --tags )
          goxz -d dist/$release_tag -z -os windows,linux -arch amd64,386
          goxz -d dist/$release_tag -z -os mac -arch amd64
          ghr -u nabeo -r mackerel-plgun-aws-transitgateway $release_tag dist/$release_tag
